'use client'

import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Ellipsis, Plus, RefreshCw } from 'lucide-react'
import { toast } from 'sonner'

import { ApiError } from '@/lib/api-client'
import { createProductCategory, createProductSubcategory, getProductCategories, getProductSubcategories, updateProductCategory, updateProductCategoryStatus, updateProductSubcategory, updateProductSubcategoryStatus, type ProductCategory, type ProductSubcategory } from '@/lib/api/product-categories'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Textarea } from '@/components/ui/textarea'
import { useAuthStore } from '@/lib/auth-store'

function errorMessage(error: unknown) { if (error instanceof ApiError && error.status === 409) return 'Ya existe un registro con esos datos.'; return error instanceof Error ? error.message : 'No se pudo completar la operación.' }

export function InventoryCategoriesPanel() {
  const tenantId = useAuthStore((state) => state.tenantId ?? 'unknown')
  const queryClient = useQueryClient()
  const categoriesQuery = useQuery({ queryKey: ['inventory-categories', tenantId], queryFn: getProductCategories, staleTime: 10 * 60 * 1000 })
  const [selectedCategory, setSelectedCategory] = useState<ProductCategory | null>(null)
  const [categoryDialog, setCategoryDialog] = useState<ProductCategory | null | false>(false)
  const [subcategoryDialog, setSubcategoryDialog] = useState<ProductSubcategory | null | false>(false)
  const subcategoriesQuery = useQuery({ queryKey: ['inventory-subcategories', tenantId, selectedCategory?.id], queryFn: () => getProductSubcategories(selectedCategory!.id), enabled: Boolean(selectedCategory), staleTime: 10 * 60 * 1000 })
  const refreshCategories = () => queryClient.invalidateQueries({ queryKey: ['inventory-categories'] })
  const refreshSubcategories = () => queryClient.invalidateQueries({ queryKey: ['inventory-subcategories', tenantId, selectedCategory?.id] })
  const statusMutation = useMutation({ mutationFn: ({ id, isActive }: { id: number; isActive: boolean }) => updateProductCategoryStatus(id, isActive), onSuccess: () => { toast.success('Estado de la categoría actualizado.'); void refreshCategories() }, onError: (error) => toast.error(errorMessage(error)) })
  const subcategoryStatusMutation = useMutation({ mutationFn: ({ id, isActive }: { id: number; isActive: boolean }) => updateProductSubcategoryStatus(selectedCategory!.id, id, isActive), onSuccess: () => { toast.success('Estado de la subcategoría actualizado.'); void refreshSubcategories() }, onError: (error) => toast.error(errorMessage(error)) })

  if (categoriesQuery.isLoading) return <div className="flex min-h-48 items-center justify-center"><RefreshCw className="size-5 animate-spin text-muted-foreground" /></div>
  if (categoriesQuery.isError) return <Card><CardContent className="flex flex-col items-center gap-3 py-12"><p className="text-sm text-destructive">No se pudieron cargar las categorías.</p><Button variant="outline" onClick={() => void categoriesQuery.refetch()}>Reintentar</Button></CardContent></Card>

  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-muted-foreground">Inventario</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Categorías</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Administra categorías y subcategorías sin eliminar registros históricos.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => void categoriesQuery.refetch()}><RefreshCw /> Actualizar</Button><Button onClick={() => setCategoryDialog(null)}><Plus /> Nueva categoría</Button></div></div>
    <Card><CardHeader><CardTitle className="text-base">Categorías de productos</CardTitle><CardDescription>Selecciona una categoría para administrar sus subcategorías.</CardDescription></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Nombre</TableHead><TableHead>Descripción</TableHead><TableHead>Productos</TableHead><TableHead>Estado</TableHead><TableHead className="w-16">Acciones</TableHead></TableRow></TableHeader><TableBody>{(categoriesQuery.data ?? []).map((category) => <TableRow key={category.id} data-state={selectedCategory?.id === category.id ? 'selected' : undefined}><TableCell className="font-medium">{category.name}</TableCell><TableCell>{category.description || '—'}</TableCell><TableCell>{category.productsCount ?? 0}</TableCell><TableCell><Badge variant={category.isActive ? 'success' : 'neutral'}>{category.isActive ? 'Visible' : 'Deshabilitada'}</Badge></TableCell><TableCell><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm" aria-label={`Acciones de ${category.name}`}><Ellipsis /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => setSelectedCategory(category)}>Ver subcategorías</DropdownMenuItem><DropdownMenuItem onClick={() => setCategoryDialog(category)}>Editar</DropdownMenuItem><DropdownMenuItem onClick={() => statusMutation.mutate({ id: category.id, isActive: !category.isActive })}>{category.isActive ? 'Deshabilitar' : 'Habilitar'}</DropdownMenuItem></DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    {selectedCategory && <Card><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle className="text-base">Subcategorías de {selectedCategory.name}</CardTitle><CardDescription>Las subcategorías siguen almacenadas aunque se deshabiliten.</CardDescription></div><Button size="sm" onClick={() => setSubcategoryDialog(null)}><Plus /> Nueva subcategoría</Button></div></CardHeader><CardContent className="p-0">{subcategoriesQuery.isLoading ? <div className="flex min-h-24 items-center justify-center"><RefreshCw className="size-5 animate-spin text-muted-foreground" /></div> : <Table><TableHeader><TableRow><TableHead>Nombre</TableHead><TableHead>Descripción</TableHead><TableHead>Estado</TableHead><TableHead className="w-16">Acciones</TableHead></TableRow></TableHeader><TableBody>{(subcategoriesQuery.data ?? []).map((subcategory) => <TableRow key={subcategory.id}><TableCell className="font-medium">{subcategory.name}</TableCell><TableCell>{subcategory.description || '—'}</TableCell><TableCell><Badge variant={subcategory.isActive ? 'success' : 'neutral'}>{subcategory.isActive ? 'Visible' : 'Deshabilitada'}</Badge></TableCell><TableCell><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm" aria-label={`Acciones de ${subcategory.name}`}><Ellipsis /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => setSubcategoryDialog(subcategory)}>Editar</DropdownMenuItem><DropdownMenuItem onClick={() => subcategoryStatusMutation.mutate({ id: subcategory.id, isActive: !subcategory.isActive })}>{subcategory.isActive ? 'Deshabilitar' : 'Habilitar'}</DropdownMenuItem></DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card>}
    <CategoryDialog key={`category-${categoryDialog === null ? 'new' : categoryDialog === false ? 'closed' : categoryDialog.id}`} open={categoryDialog !== false} category={categoryDialog || null} onOpenChange={(open) => !open && setCategoryDialog(false)} onSaved={() => { setCategoryDialog(false); void refreshCategories() }} />
    {selectedCategory && <SubcategoryDialog key={`subcategory-${subcategoryDialog === null ? 'new' : subcategoryDialog === false ? 'closed' : subcategoryDialog.id}`} open={subcategoryDialog !== false} categoryId={selectedCategory.id} subcategory={subcategoryDialog || null} onOpenChange={(open) => !open && setSubcategoryDialog(false)} onSaved={() => { setSubcategoryDialog(false); void refreshSubcategories() }} />}
  </div>
}

function CategoryDialog({ open, category, onOpenChange, onSaved }: { open: boolean; category: ProductCategory | null; onOpenChange: (open: boolean) => void; onSaved: () => void }) { return <EntityDialog open={open} title={category ? 'Editar categoría' : 'Nueva categoría'} initialName={category?.name ?? ''} initialDescription={category?.description ?? ''} save={(name, description) => category ? updateProductCategory(category.id, { name, description }) : createProductCategory({ name, description })} onOpenChange={onOpenChange} onSaved={onSaved} /> }
function SubcategoryDialog({ open, categoryId, subcategory, onOpenChange, onSaved }: { open: boolean; categoryId: number; subcategory: ProductSubcategory | null; onOpenChange: (open: boolean) => void; onSaved: () => void }) { return <EntityDialog open={open} title={subcategory ? 'Editar subcategoría' : 'Nueva subcategoría'} initialName={subcategory?.name ?? ''} initialDescription={subcategory?.description ?? ''} save={(name, description) => subcategory ? updateProductSubcategory(categoryId, subcategory.id, { name, description }) : createProductSubcategory(categoryId, { name, description })} onOpenChange={onOpenChange} onSaved={onSaved} /> }
function EntityDialog({ open, title, initialName, initialDescription, save, onOpenChange, onSaved }: { open: boolean; title: string; initialName: string; initialDescription?: string | null; save: (name: string, description: string) => Promise<unknown>; onOpenChange: (open: boolean) => void; onSaved: () => void }) { const [name, setName] = useState(initialName); const [description, setDescription] = useState(initialDescription ?? ''); const [error, setError] = useState(''); const mutation = useMutation({ mutationFn: () => save(name.trim().toUpperCase(), description), onSuccess: onSaved, onError: (value) => setError(errorMessage(value)) }); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{title}</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); setError(''); if (!name.trim()) return setError('El nombre es obligatorio.'); mutation.mutate() }}><div className="space-y-2"><Label>Nombre *</Label><Input value={name} onChange={(event) => setName(event.target.value)} autoFocus /></div><div className="space-y-2"><Label>Descripción</Label><Textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={3} /></div>{error && <p className="text-sm text-destructive">{error}</p>}<DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending && <RefreshCw className="animate-spin" />} Guardar</Button></DialogFooter></form></DialogContent></Dialog> }
