'use client'

import { useEffect, useState } from 'react'
import { Loader2, Pencil, Plus, ToggleLeft, ToggleRight } from 'lucide-react'
import { toast } from 'sonner'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { createMedicalPlan, getMedicalPlans, setMedicalPlanStatus, updateMedicalPlan, type MedicalPlan } from '@/lib/api/subscriptions'

const money = (value: number) => new Intl.NumberFormat('es-UY', { style: 'currency', currency: 'UYU' }).format(value)
const periodicityLabels = { MONTHLY: 'Mensual', QUARTERLY: 'Trimestral', SEMIANNUAL: 'Semestral', ANNUAL: 'Anual' }

export default function MedicalPlansPage() {
  const [plans, setPlans] = useState<MedicalPlan[]>([])
  const [loading, setLoading] = useState(true)
  const [open, setOpen] = useState(false)
  const [editing, setEditing] = useState<MedicalPlan | null>(null)
  const [saving, setSaving] = useState(false)

  const load = async () => { setLoading(true); try { setPlans(await getMedicalPlans()) } catch { toast.error('No se pudieron cargar los planes.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const toggle = async (plan: MedicalPlan) => { try { await setMedicalPlanStatus(plan.id, plan.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE'); toast.success('Estado del plan actualizado.'); await load() } catch { toast.error('No se pudo actualizar el estado.') } }

  return <div className='space-y-6'>
    <div className='flex flex-wrap items-start justify-between gap-4'><div><h1 className='text-2xl font-semibold tracking-tight'>Planes veterinarios</h1><p className='text-sm text-muted-foreground'>Configura la cobertura que contratan tus clientes.</p></div><Button onClick={() => { setEditing(null); setOpen(true) }}><Plus className='mr-2 size-4' />Nuevo plan</Button></div>
    <Card><CardHeader><CardTitle>Listado de planes</CardTitle></CardHeader><CardContent className='grid gap-3 md:grid-cols-2 xl:grid-cols-3'>{loading ? <p className='text-sm text-muted-foreground'>Cargando planes...</p> : plans.length === 0 ? <p className='text-sm text-muted-foreground'>Todavía no hay planes configurados.</p> : plans.map((plan) => <div key={plan.id} className='rounded-xl border border-slate-200 p-4'><div className='flex items-start justify-between gap-3'><div><h2 className='font-semibold'>{plan.name}</h2><p className='mt-1 text-sm text-muted-foreground'>{plan.description || 'Sin descripción'}</p></div><Badge variant={plan.status === 'ACTIVE' ? 'success' : 'neutral'}>{plan.status === 'ACTIVE' ? 'Activo' : 'Inactivo'}</Badge></div><div className='mt-4 grid grid-cols-2 gap-3 text-sm'><div><p className='text-xs text-muted-foreground'>Precio</p><p className='font-semibold'>{money(Number(plan.price))}</p></div><div><p className='text-xs text-muted-foreground'>Periodicidad</p><p className='font-semibold'>{periodicityLabels[plan.periodicity]}</p></div><div><p className='text-xs text-muted-foreground'>Mascotas</p><p className='font-semibold'>Hasta {plan.maxPets}</p></div><div><p className='text-xs text-muted-foreground'>Mora</p><p className='font-semibold'>{plan.applyLateFee ? `${plan.lateFeeType} · ${plan.lateFeeValue}` : 'No aplica'}</p></div></div><div className='mt-4 flex justify-end gap-1'><Button variant='ghost' size='icon' aria-label='Editar plan' onClick={() => { setEditing(plan); setOpen(true) }}><Pencil className='size-4' /></Button><Button variant='ghost' size='icon' aria-label={plan.status === 'ACTIVE' ? 'Desactivar plan' : 'Activar plan'} onClick={() => void toggle(plan)}>{plan.status === 'ACTIVE' ? <ToggleLeft className='size-4' /> : <ToggleRight className='size-4' />}</Button></div></div>)}</CardContent></Card>
    <PlanForm open={open} onOpenChange={setOpen} editing={editing} saving={saving} setSaving={setSaving} onSaved={async () => { setOpen(false); await load() }} />
  </div>
}

function PlanForm({ open, onOpenChange, editing, saving, setSaving, onSaved }: { open: boolean; onOpenChange: (open: boolean) => void; editing: MedicalPlan | null; saving: boolean; setSaving: (value: boolean) => void; onSaved: () => Promise<void> }) {
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [price, setPrice] = useState(''); const [periodicity, setPeriodicity] = useState<MedicalPlan['periodicity']>('MONTHLY'); const [maxPets, setMaxPets] = useState('1'); const [applyLateFee, setApplyLateFee] = useState(false); const [lateFeeType, setLateFeeType] = useState<MedicalPlan['lateFeeType']>('NONE'); const [lateFeeValue, setLateFeeValue] = useState('0'); const [benefits, setBenefits] = useState('{}')
  useEffect(() => { if (open) { setName(editing?.name || ''); setDescription(editing?.description || ''); setPrice(editing ? String(editing.price) : ''); setPeriodicity(editing?.periodicity || 'MONTHLY'); setMaxPets(editing ? String(editing.maxPets) : '1'); setApplyLateFee(editing?.applyLateFee || false); setLateFeeType(editing?.lateFeeType || 'NONE'); setLateFeeValue(editing ? String(editing.lateFeeValue) : '0'); setBenefits(editing ? JSON.stringify(editing.benefits, null, 2) : '{}') } }, [open, editing])
  const submit = async () => { let parsedBenefits: unknown; try { parsedBenefits = JSON.parse(benefits) } catch { toast.error('Los beneficios deben ser un JSON válido.'); return } if (!name.trim() || !price || Number(price) < 0) { toast.error('Completa nombre y precio.'); return } setSaving(true); try { const data = { name: name.trim(), description: description.trim() || null, price: Number(price), benefits: parsedBenefits, periodicity, maxPets: Number(maxPets), applyLateFee, lateFeeType: applyLateFee ? lateFeeType : 'NONE' as const, lateFeeValue: applyLateFee ? Number(lateFeeValue) : 0 }; if (editing) await updateMedicalPlan(editing.id, data); else await createMedicalPlan(data); toast.success(editing ? 'Plan actualizado.' : 'Plan creado.'); await onSaved() } catch { toast.error('No se pudo guardar el plan.') } finally { setSaving(false) } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className='max-w-xl'><DialogHeader><DialogTitle>{editing ? 'Editar plan veterinario' : 'Nuevo plan veterinario'}</DialogTitle><DialogDescription>Los cambios no alteran el precio contratado de suscripciones existentes.</DialogDescription></DialogHeader><div className='grid gap-4 sm:grid-cols-2'><div className='space-y-1.5 sm:col-span-2'><Label>Nombre</Label><Input value={name} onChange={(e) => setName(e.target.value)} placeholder='Plan Premium' /></div><div className='space-y-1.5 sm:col-span-2'><Label>Descripción</Label><Input value={description} onChange={(e) => setDescription(e.target.value)} /></div><div className='space-y-1.5'><Label>Precio</Label><Input type='number' min='0' step='0.01' value={price} onChange={(e) => setPrice(e.target.value)} /></div><div className='space-y-1.5'><Label>Mascotas máximas</Label><Input type='number' min='1' step='1' value={maxPets} onChange={(e) => setMaxPets(e.target.value)} /></div><div className='space-y-1.5'><Label>Periodicidad</Label><Select value={periodicity} onValueChange={(value) => setPeriodicity(value as MedicalPlan['periodicity'])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(periodicityLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><div className='space-y-1.5'><Label>Mora</Label><Select value={applyLateFee ? lateFeeType : 'NONE'} onValueChange={(value) => { setApplyLateFee(value !== 'NONE'); setLateFeeType(value as MedicalPlan['lateFeeType']) }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value='NONE'>No aplica</SelectItem><SelectItem value='FIXED'>Importe fijo</SelectItem><SelectItem value='PERCENTAGE'>Porcentaje</SelectItem></SelectContent></Select></div>{applyLateFee && <div className='space-y-1.5'><Label>Valor de mora</Label><Input type='number' min='0' step='0.01' value={lateFeeValue} onChange={(e) => setLateFeeValue(e.target.value)} /></div>}<div className='space-y-1.5 sm:col-span-2'><Label>Beneficios (JSON)</Label><Textarea value={benefits} onChange={(e) => setBenefits(e.target.value)} className='min-h-24 font-mono text-xs' /></div></div><DialogFooter><Button variant='outline' onClick={() => onOpenChange(false)} disabled={saving}>Cancelar</Button><Button onClick={() => void submit()} disabled={saving}>{saving && <Loader2 className='mr-2 size-4 animate-spin' />}{editing ? 'Guardar cambios' : 'Crear plan'}</Button></DialogFooter></DialogContent></Dialog>
}
